version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteksql
    ports:
      - "3306:3306"

  bibliotek:
    image: bibliotek
    build: .
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
