version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-bibliotek
    ports:
      - 27017:27017

  mongo-express-bibliotek:
    image: mongo-express
    ports:
      - 8081:8081

    depends_on:
      - mongo





