version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-bibliotek
    ports:
      - 27017:27017

  mongo-express-bibliotek:
    image: mongo-express
    ports:
      - 8081:8081

    depends_on:
      - mongo

  bibliotek:
    image: bibliotek
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: bibliotek
    depends_on:
      - mongo