name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [closed]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'

      - name: Build Jar
        run: mvn test